version: '3'
services:
  app:
    image: kamsid/biggames
    build: .
    command: gunicorn --bind=0.0.0.0:8000 BG.wsgi:application
    volumes:
      - /BG/static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - envs/.env.deploy
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=kamen
      - POSTGRES_PASSWORD=kamsid
      - PGDATA:/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /BG/static:/home/app/BG/static
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - app
