version: '3'

services:
  django_app:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - db
    env_file:
      - ./envs/.env
#    volumes:

  db:
    image: postgres

    environment:
      - POSTGRES_DB=test_database
      - POSTGRES_USER=kamen
      - POSTGRES_PASSWORD=kamsid
