# Generated by Django 4.2.1 on 2023-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_remove_replay_video_resource_replay_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='game',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
