# Generated by Django 4.2.1 on 2023-06-04 05:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdb', '0004_replay_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replay',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
