# Generated by Django 4.2.1 on 2023-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_alter_replay_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='likes_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
