# Generated by Django 4.2.1 on 2023-07-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdb', '0007_replay_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='replay',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='replay',
            name='likes',
            field=models.ManyToManyField(related_name='liked_replays', to=settings.AUTH_USER_MODEL),
        ),
    ]
