# Generated by Django 4.2.1 on 2023-07-08 06:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_alter_replay_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='accounts.AppUser'),
        ),
    ]
