# Generated by Django 4.2.1 on 2023-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0010_alter_replay_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
