# Generated by Django 4.2.1 on 2023-07-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0014_rename_video_replay_video_url_replay_video_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['title'], 'permissions': [('can_add_replay', 'Can add replay'), ('can_change_replay', 'Can change replay'), ('can_delete_replay', 'Can delete replay')]},
        ),
        migrations.RemoveField(
            model_name='replay',
            name='likes',
        ),
    ]
