# Generated by Django 4.2.1 on 2023-07-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_like_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
