# Generated by Django 4.2.1 on 2023-07-08 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('steam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(upload_to='profile_pictures/')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
