# Generated by Django 4.2.1 on 2023-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='steam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
