# Generated by Django 4.2.1 on 2023-07-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_appuserprofile_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='steam_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
