# Generated by Django 4.2.1 on 2023-07-22 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0015_alter_replay_options_remove_replay_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0009_guild_appuserprofile_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.replay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
