# Generated by Django 4.2.1 on 2023-07-22 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0010_alter_appuserprofile_picture_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuserprofile',
            name='guild',
        ),
        migrations.AlterField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(related_name='guild', to=settings.AUTH_USER_MODEL),
        ),
    ]
